import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Button } from "@repo/ui/button";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Button appName="web">Click me</Button>
        {children}
      </body>
    </html>
  );
}
